export const data = [
  {
    week: 1,
    sleepQuality: 30,
    anxiety: 10,
    depression: 20,
    fatigue: 30,
    negativeThoughts: 30,
    gutConcerns: 70,
  },
  {
    week: 2,
    sleepQuality: 37,
    anxiety: 6,
    depression: 18,
    fatigue: 30,
    negativeThoughts: 28,
    gutConcerns: 67,
  },
  {
    week: 3,
    sleepQuality: 39,
    anxiety: 6,
    depression: 17,
    fatigue: 28,
    negativeThoughts: 27,
    gutConcerns: 65,
  },
  {
    week: 4,
    sleepQuality: 50,
    anxiety: 4,
    depression: 8,
    fatigue: 24,
    negativeThoughts: 15,
    gutConcerns: 35,
  },
  {
    week: 5,
    sleepQuality: 60,
    anxiety: 5,
    depression: 10,
    fatigue: 26,
    negativeThoughts: 17,
    gutConcerns: 40,
  },
  {
    week: 6,
    sleepQuality: 90,
    anxiety: 1,
    depression: 0,
    fatigue: 2,
    negativeThoughts: 2,
    gutConcerns: 10,
  },
  {
    week: 7,
    sleepQuality: 92,
    anxiety: 0,
    depression: 0,
    fatigue: 2,
    negativeThoughts: 1,
    gutConcerns: 8,
  },
  {
    week: 8,
    sleepQuality: 90,
    anxiety: 1,
    depression: 0,
    fatigue: 1,
    negativeThoughts: 1,
    gutConcerns: 10,
  },
  {
    week: 9,
    sleepQuality: 80,
    anxiety: 2,
    depression: 7,
    fatigue: 5,
    negativeThoughts: 5,
    gutConcerns: 20,
  },
  {
    week: 10,
    sleepQuality: 83,
    anxiety: 1,
    depression: 5,
    fatigue: 3,
    negativeThoughts: 5,
    gutConcerns: 17,
  },
  {
    week: 11,
    sleepQuality: 77,
    anxiety: 2,
    depression: 6,
    fatigue: 5,
    negativeThoughts: 10,
    gutConcerns: 25,
  },
  {
    week: 12,
    sleepQuality: 80,
    anxiety: 3,
    depression: 2,
    fatigue: 3,
    negativeThoughts: 6,
    gutConcerns: 22,
  },
  {
    week: 13,
    sleepQuality: 85,
    anxiety: 1,
    depression: 2,
    fatigue: 4,
    negativeThoughts: 4,
    gutConcerns: 15,
  },
  {
    week: 14,
    sleepQuality: 90,
    anxiety: 1,
    depression: 1,
    fatigue: 2,
    negativeThoughts: 2,
    gutConcerns: 12,
  },
  {
    week: 15,
    sleepQuality: 80,
    anxiety: 1,
    depression: 2,
    fatigue: 3,
    negativeThoughts: 3,
    gutConcerns: 15,
  },
  {
    week: 16,
    sleepQuality: 75,
    anxiety: 1,
    depression: 1,
    fatigue: 4,
    negativeThoughts: 2,
    gutConcerns: 14,
  },
  {
    week: 17,
    sleepQuality: 80,
    anxiety: 2,
    depression: 1,
    fatigue: 3,
    negativeThoughts: 3,
    gutConcerns: 15,
  },
  {
    week: 18,
    sleepQuality: 80,
    anxiety: 0,
    depression: 0,
    fatigue: 1,
    negativeThoughts: 1,
    gutConcerns: 12,
  },
  {
    week: 19,
    sleepQuality: 70,
    anxiety: 1,
    depression: 0,
    fatigue: 2,
    negativeThoughts: 1,
    gutConcerns: 12,
  },
];
